@server=http://localhost:3000/api
@createdTableId={{createTable.response.body.id}}
@createdChainId={{createChain.response.body.id}}
@createdRuleId={{createRule.response.body.id}}
@createdLogId={{createLog.response.body.id}}

### Get configuration (tables, chains and rules)
GET {{server}}/db

### ──────────────────────────────────────────────────────────────────
###                               TABLES
### ──────────────────────────────────────────────────────────────────

### Create a table
# @name createTable
POST {{server}}/tables
Content-Type: application/json

{
  "name": "filter",
  "family": "ip6",
  "description": "Tabela principal de filtragem de pacotes IPv6"
}

### Get all tables
GET {{server}}/tables

### Get table by ID
GET {{server}}/tables/2

### Update table by ID
PUT {{server}}/tables/3
Content-Type: application/json

{
  "name": "filter",
  "family": "ip4",
  "description": "Tabela principal de filtragem de pacotes IPv4"
}

### Remove table by ID
DELETE {{server}}/tables/2

### ──────────────────────────────────────────────────────────────────
###                               CHAINS
### ──────────────────────────────────────────────────────────────────

### Create a chain
# @name createChain
POST {{server}}/chains
Content-Type: application/json

{
  "table_id": "cadqhx57ab5lk5u86n4q61w2",
  "name": "input",
  "type": "filter",
  "hook": "input",
  "priority": "2",
  "policy": "accept",
  "description": "Cadeia para tráfego de entrada no sistema com prioridade 2, política de aceitação"
}

### Get all chains
GET {{server}}/chains

### Get chain by ID
GET {{server}}/chains/{{createdChainId}}

### Update chain by ID
PUT {{server}}/chains/{{createdChainId}}
Content-Type: application/json

{
  "table_id": "t1",
  "name": "input",
  "type": "filter",
  "hook": "input",
  "priority": "3",
  "policy": "deny",
  "description": "Cadeia para tráfego de entrada no sistema com prioridade 3, política de negação"
}

### Remove chain by ID
DELETE {{server}}/chains/{{createdChainId}}

### ──────────────────────────────────────────────────────────────────
###                               RULES
### ──────────────────────────────────────────────────────────────────

### Create a rule
# @name createRule
POST {{server}}/rules
Content-Type: application/json

{
  "chain_id": "c1",
  "position": 1,
  "description": "Permitir interface loopback",
  "matches": [
    {
      "type": "interface",
      "interface": "lo",
      "direction": "input"
    }
  ],
  "action": "accept",
  "counter": true,
  "enabled": true
}

### Get all rules
GET {{server}}/rules

### Get rule by ID
GET {{server}}/rules/{{createdRuleId}}

### Update rule by ID
PUT {{server}}/rules/{{createdRuleId}}
Content-Type: application/json

{
  "chain_id": "c1",
  "position": 1,
  "description": "Proibir interface loopback",
  "matches": [
    {
      "type": "interface",
      "interface": "lo",
      "direction": "input"
    }
  ],
  "action": "drop",
  "counter": true,
  "enabled": true
}

### Remove rule by ID
DELETE {{server}}/rules/{{createdRuleId}}

### ──────────────────────────────────────────────────────────────────
###                                LOGS
### ──────────────────────────────────────────────────────────────────

### Create log
# @name createLog
POST {{server}}/logs
Content-Type: application/json

{
  "date": "2025-12-05",
  "time": "19:55:01",
  "source_ip": "10.25.50.164",
  "source_port": "44444",
  "dest_ip": "10.25.50.1",
  "dest_port": "200",
  "action": "Allow"
}

### Get all logs
GET {{server}}/logs

### Get log by ID
GET {{server}}/logs/{{createdLogId}}

### Update log by ID
PUT {{server}}/logs/{{createdLogId}}
Content-Type: application/json

{
  "date": "2025-12-06",
  "time": "20:55:01",
  "source_ip": "10.25.50.164",
  "source_port": "44444",
  "dest_ip": "10.25.50.1",
  "dest_port": "200",
  "action": "Block"
}

### Remove log by ID
DELETE {{server}}/logs/{{createdLogId}}

### ──────────────────────────────────────────────────────────────────
###                               USERS
### ──────────────────────────────────────────────────────────────────

### Signup (Cadastro de usuário)
POST {{server}}/signup
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@firewallwizard.com",
  "password": "123456"
}

### ──────────────────────────────────────────────────────────────────
###                               AUTH
### ──────────────────────────────────────────────────────────────────

### Login
POST {{server}}/login
Content-Type: application/json

{
  "email": "admin@firewallwizard.com",
  "password": "123456"
}
